apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sitio-rails-sqlite
  namespace: sitio-staging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
