---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sitio-rails-secrets
  namespace: sitio-staging
spec:
  encryptedData:
    RAILS_MASTER_KEY: AgBvnSulY22sTKwTEvu/f6oxGQT1ReWnhfUwtjuPGIS835u3MrhHQE82GvXaHXb0wB/TKIsfrek63wKtKH/cS6jFcXyIAvhhraJDFVmnPc04UfzyAoVSnWQz7kQdXQY/vnYq2ldzgUbLX6WxZtmfF9e8N0JzguSNrTucwz8idEGhahpIaX9J2uuusYGtzegAOBpsM2JUY/KkjVMAgwJ8T+DR9K71i+jAzrgzTfB2nnfezpykuwp4Q+GXN8vHDBcXQ880LS3M+y3QWnLLBMFqEWwBujyZbQRiJI3U5+l5vYzEDKQzf68pib82B5T4ITCaB+Tyn3kRU16xVW0QcpLJIXnlF7BRQmvKqI8VKwPRd8brH196jmMQBu13JVn0MzeRFXYnJN7fXt/c2fdI5huAdROBj2NN4wJal2TUEuLdwfqfarwAvagr9m48t4MhGUUs+VUbjkcJxRR/BwPJ5RYyl7zi7QLGbOhw1VMF3SD9nytieF7nMEAOpGzg1z4B9NIpH+uXNjGxGbbbfeD68fwIQ299J/B9nFZTthHWDNO0bGG31X4tcH95VcFCzm7/mvAp66WVTVYUxUs712iJsn5AyfpFFTghyo7S3iKyBo4GGiWakHcyQVmRRbZ9v8jweYfEPR4hrih7G4ohNDCNthim77vTHeTg1Rsh862K8/UgFOPaUco7HhxZy4YgqKSqmXIbkMYAIC6CVL7Svh3eAulkh7KfQdcT/1zcUZLknIEeXQE3rg==
  template:
    metadata:
      name: sitio-rails-secrets
      namespace: sitio-staging
    type: Opaque
