---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgBSks4LCiXYp6tcVWrpuf9xbnk6mUYfjibudB0WH6SkUu/f0If9q6flzCLrETqpn3+gXSEVfxWJJBYoQqYZBSoOhvLa0PhHXDTuXY8ScMxe340RZB4OVLLKiwira4wQA2urL6nNBZ+0sHWQFaIOYEZj78lJKIYsqF1NXh0CxbbtY7CmEmrvjz0Q6AsYiLazhFZr0GPYB2m88DuVE5SmjEaaYVOuJVhusFKZSqcy5iCCO0WJqo6krvI6wmNEYm113DpaO6UegTkhrWUt9ti8vrU34fFY6SgE6AfZATO9wvpvseQWRWCnsWGfy8ODNqJIkuC0JLyA8yA3D+Sl19R8hudAZME+FWeqaux8RwC1XQ5d3TdlsH6jHRmqNSLjnoeCallK737rUf6syc6/boH+A8NB3fd31ZKunUMp+oXGAngCvqvVW7BR+MdMT0dWTk0/UN+qdcyC26OOkCrPlFOX8/8kvTbcEw/8UqL6FR3S6YmdgZUYGaT9DR5OTwgJPKA7pI9ADoPlQvDXnzo3YcdongQKNwqFKE71w4z9H9Lp+KXU//4aNZ898kEjYCln967ojs/fUSwhgyd+mhZmRmYYzMi2ZocKav9kIbTJxM8t6H41EAH1ZheHZFB+sFZIFLEgRxUlzhkK5X4iGTNRgpOJd5ZIevx4zckFFWB3TMzmc9YFBr/LEodWlkqYWI9F81dLC2Ob2iFankWrLh5grJy6L8Siv4DGeuivWZ3aiVfVh9SV+A==
  template:
    metadata:
      name: argocd-oidc-secret
      namespace: argocd
