---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgAEabcusTN0qCynqcbpqOT2rbIcjKBlTb8ksjAOg7dhgWIYyeCNUSfJAkIp+iPfPx5JRIrgE62hy8JrPgIEQ35XMC35BrxKZAm7kPL/S++9aF9Iwvau85O20X3jGL7VCTLCmCd6fjAYoVhhcfXkWz7Sb4PejfCYai/4g/OYXSZQaO94+NMx82wFHJzEXIjQ8/n+My3TPtInhJ5qL6GGcb0jxmreJe3k/PMuuGEZG5SEHgzyoCBIbbhyWSf9u1GwF5RHIoM+7kWPw3NxzpMBgvlP+kweju1wIuDLfNLcSHZON2QgZIlTmbZtRsZaaAFwnEi4cgFN22qBf/fsn2xt+tplOASV3H0vUFoXEZEDL9Mo6GoG32vIggzDgl7nCdILQSWh/Yw/4uHU1tqGIjrIUBAy5gRx4HS2k2io1ou3MfQIe2dIi71zWUrcsg10n4TvRFQzlqHb02iXo5Z/WC1IuOnZ+0VbikNWawLZJHNQdWMiwqiX6iTW0/GP39hRO5RWvCEkumphW87z9Xekkdf7T+dYQBjy7CIivyAtMyNmZO8khje6unU52KbY+lAho8izrt/acZ/ZPdFV99wBPEPFIh/XPKrCSZIoKBAV+SbiNd1hzpVZNaSlPxxHpGkfTjhOQctHvoDn+tDkEjp+JhafyZmWQA3LZhHsG2ULjRR4KJwwvG9jPCdsGdtMdJpjzRPXY8lLH/JZgv6bz2BTDMdF0jWGjyoYuLt091oWmMgqeC2Sng==
  template:
    metadata:
      name: argocd-oidc-secret
      namespace: argocd
