{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "argocd-oidc-secret",
    "namespace": "argocd"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "argocd-oidc-secret",
        "namespace": "argocd",
        "labels": {
          "app.kubernetes.io/part-of": "argocd"
        }
      }
    },
    "encryptedData": {
      "clientSecret": "AgAus4T2plqLD2nVGLhvmU9s35u/Fr6RTwfMjr377OahaCM7U3eIgvvpq1jKJIya0maHy7aedLRTG7leqbIhOwtM/tH09DD5owXRYQL3IRsWVziEmPDhKvoA13fkYtMKaNd6bhV1/wZAxdAi7fDc9EFyq3g49QbzYrmidLvWXkQle4+r9cuXWtk3bPAGeEZCbkOa/8Fd3qH/WQsArJOw155YDbvgJCFyBCZLYyP9IAQZrsMVF6QsSi7yPfo8zdFCR2cHEQXQtQWoT09IE1hJK8+bPojB09d5IBC4mwaSyyYm5mEi5mx+0pVMZXrPeLjaNPpb7V4Jkdz5mfLEvptC4QQFbzJ/8IMhPNslstVT0MGXxSWAHmYxBv+eMj1Q4zAGFkV9ZdG07JZI7Z5HDV1gwnQkdnfA3uqXQIbaI5VuYXtbgm9wIbJiSShZihMKRsCRvJO/gPszjtbOA6SvdmCZ+LUTpGiHbLKAvcp0/OwPNbZTRJvMcXuoWxa9g7+MJj2vxywWpEN9a764B2ZIFIyNGEXN/2QcjrAHMi+Fv+ob/Ocew1A3xQ8E2jqUR9vqbe25LofXHk0ndpvkRaDUcPVMI/nULPmZGrMyCRikqjWwi1kmpLLk/vtXUGrCro5gBGtHRx+aLLke/AOkvjVbaslMnJrD3UPFlCgAYctsd6FyvTxf9rl65jBVTZ+/kAM7b4F4RoVfNfeg1hq8jR9K4tL8/tSTnQVTgLF7pVqiAyW0dwdnBw=="
    }
  }
}
