apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
  namespace: platform
data:
  config.yaml: |
    server:
      database: "/home/filebrowser/data/database.db"
      sources:
        - path: "/srv"
          config:
            defaultEnabled: true
    auth:
      adminUsername: admin

