---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocir-pull
  namespace: sitio-staging
spec:
  encryptedData:
    .dockerconfigjson: AgBjFvwc/0Iaacyd/xI5COLUNQifZFzwA+fuGTckijvFNw+7Kmf3f0ncVWf/dl4KIQddF/WzdREYCrVZvclV/4OXf+lTqNS16uZEoLY6yaQQZkpS1wL1trGhoKYiqyro4ZvyTN88DDpxEhf2NNFSo4Q64w7O1UOOQBxdC9oMaggCVp6PQh9cwtDQdey+fPXSssKvxvD7mDkbI29pOEbMjCed1YncluR8u/U3QKOqcvYYRdEd92jSEKdu1Di8ROkR6bfgKNsMxUUojFL1lvLBQbnGB3WaeTI8QIOflsG4fP5UrXKiaQhO/xvPmf6S6jaVpJ8a9xgjWoqlhT1FIn2HPSazvH6UdH3Nl/DV7oh9j83cuneWr91kKhCs43YdCDTmqtA7zO7hS75Vo2n6dqQnTBQLLIB82Wh/bOhgPxkp6eL/whgmllVJBtaAIU9OD09CPaUxZVbipNbf5Nsy0wZ5ErKVDBtrea4RcCbvkMWTFI65fJJ6pgJsxHXyz5xuhbzLegEpMBdalwhbmNqgApzLF0TOpx2kCev8JPaRqzWx7CwI7wMDFCwMtPIAoE7Ee+tVCK3Nttc1+mw1HN3YqRfPiVzJik4Z+M32rxc8wsuuIgXN9HW7ciJCGYjXV8fl0WI5GlfEitp/7V7sJC+KgOeIFkNGWn5gs5GQLR3mOKiQBACtUTZW0A99hIY1rWoGZZUFyGaU9BDvVS9enTEpCXH6Nca8xa5TtKjyh9h4Ow33it2w9bxAie7DaoY7UEqxxW5PP1fVd0NlIRGh74hNU+F/Ii0IRg1SiT8vntjvTvctQH6zXjXDo2Y/WjSqPj8ivXs3oR9wBcAMTpiAoZ/fTh/yBxo9XPEmHGi2c0xJQ70VCZfw2Yhj3HugaAeDcOXJ/gQbRNfbzOGYWD6jwVxPhUG5oTH6N3fx5W0iDENrCW4f+7VTUbVLRweMolu1WGpZcoBkMSDoUN/grPRaylsfynO7JIMUDUDVoPtYBT7hPWAR+GdQsNIvobIt8iiLfqHkqroQpN2yxII=
  template:
    metadata:
      name: ocir-pull
      namespace: sitio-staging
    type: kubernetes.io/dockerconfigjson
