apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sitio-backend
  namespace: sitio-staging
  labels:
    app: sitio-backend
spec:
  selector:
    matchLabels:
      app: sitio-backend
  namespaceSelector:
    matchNames:
      - sitio-staging
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
