apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketid
  namespace: platform
  labels:
    app: pocketid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocketid
  template:
    metadata:
      labels:
        app: pocketid
    spec:
      initContainers:
        - name: nfs-mount
          image: docker.io/library/busybox:1.36
          command:
            - sh
            - -c
            - |
              mount -t nfs -o vers=4 nfs-server.platform.svc.cluster.local:/platform-pocketid /shared/data
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /shared/data
              mountPropagation: Bidirectional
      containers:
        - name: pocketid
          image: docker.io/11notes/pocket-id:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: APP_URL
              value: "https://pocketid.artr.com.br"
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: pocketid-credentials
                  key: encryption-key
            - name: TRUST_PROXY
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /data
              mountPropagation: HostToContainer
      volumes:
        - name: data
          emptyDir: {}

