apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-pocketid-data
  namespace: platform
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client

