apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-pocketid-data
  namespace: platform
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: platform-pocketid-pv
  storageClassName: ""        # must match PV

