apiVersion: v1
kind: Service
metadata:
  name: pocketid
  namespace: platform
  labels:
    app: pocketid
spec:
  selector:
    app: pocketid
  ports:
    - name: http
      port: 1411
      targetPort: 1411

