apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-tailscale-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: "1.98.4"
      helm:
        releaseName: tailscale-operator
        valueFiles:
          - $values/charts/tailscale-operator-values.yaml
    - repoURL: https://github.com/artieeez/artr-gitops
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
