apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      initContainers:
        - name: create-dirs
          image: docker.io/library/busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /exports/staging-postgre /exports/platform-filebrowser
          volumeMounts:
            - name: exports
              mountPath: /exports
      containers:
        - name: nfs-server
          image: docker.io/itsthenetwork/nfs-server-alpine:11-arm
          env:
            - name: SHARED_DIRECTORY
              value: /exports
          ports:
            - containerPort: 2049
              name: nfs
          securityContext:
            privileged: true
          volumeMounts:
            - name: exports
              mountPath: /exports
      volumes:
        - name: exports
          persistentVolumeClaim:
            claimName: nfs-server-pvc
