---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-secrets
  namespace: production
spec:
  encryptedData:
    RAILS_MASTER_KEY: AgB+xXM7POZ6HxpW1sXN05belV5SvsJ0ZVJ4mkr37UreX8KWxqSEeoqzB79AdX+oAhLmfexyhrFhQc/CHtBwJTeyhFkyY3KIkEEVjD9a3TKRgHiVprCDtEUr+ndRl555tBLUqeynDdW1GGpgJgCwOIC6Ecl85/Xw5FxPvUbtIfE/WF9kcVjC7DS+VKqEefR6P8q2OeqvKzNTJHsPAXy+cELei+hrLGfpl2GQqh2SAVwakdfXqT9uYwY3BBse3+xagb1K0Fdw6Gb5ytdviDgsmX1zV5dIOEJACcHJVBx0zr1TJCdJN7ee/xU+rKRPdgW5dSzKR024FOELll4mdKPmIGtPp8ZBR4iRPtT/pwGjfyNvoD8nzVkPrZmfuxxLWX0emM8Jx11/uZWxQOP2HLfH7XjB4Vhq6i7/aPGc9vIEfCeN/rA+Yhx4dJQzVS90hcTxUWXw0d/+pQ3/pseTy3ek9kMlwdu4WVTLYflFqOc8qq1yEqJC+Wx1moEm3KW9O0JnnTdp0nrpfE1m/vjX+cEoY25q+xDV/pXJJ00FZFjQALz7Ja7xgE2UL6zJF7I9gBjalsgQNAaJ5gVj4JNyBC7Br9TSKVR4R79SfjUjHK0qOw2Qc5gWHpzN6rfmKfOIuPUlNl4D6o/Lqh8Tuojzbw0X4TIDLa8Mg+Uqe6dw4YXqMeurdCuf3WWFjey1PhnyWvP68oVzCg6T0B4BfZNBmNkREfpLpb+90xiHjV4wKG5TWKVe5g==
  template:
    metadata:
      name: home-secrets
      namespace: production
