---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocir-pull
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgBYcuSKWA8Xl/EjZtGwIs/Q5OpshlWn+ggA8AP/2q6pzODfP10XzsZ+/u42WM/vt1uB2vdz6FRpIuvlo4S7osHYw90h3hPHm4LMr7zx2NIr2BZeDRiRc8blgYF3fIzqx8cWpPXKj25Nk1KMw03oeavdMk3XW00nvTWpT4IVmFMbrk6tmJqdm4et7oo8jjaUBKixdCSGYwrJjxaKwknQiLYiekggQVjMhatbNR0JwN7Vpc2QM7k0w9JOeHxa0k8fHZRwfQiRp+NycmCoCYd0V8uMYYVK1kvu3QLcSYYP2oZBsBAT90FsRXeJ7CSq8UVr3hLbsUiaVIE/wvV69aNV2sV1KTTJNivqf8dyEQfUse05D2Gh8PlDcg/cy62uFCQIvMVLqonFucTVBLS5Rgrv0Q4JRBYc3vikUf/3fRfxog8L1l6jgnXRpjlVD0oH9i/c3opUmtsQ3G+vUr89jd0nb9WUpfR2y295ZlSAw8VdBspvziXcKzM1DXohz9JRlq0C2ZkxXyNeb3thMRW+chaGPPirr9suJh2hUwpflTqjgNcw5xzq4Dppylt71wnMkqp0xHl4GujyDZNSsFwwk9WVN5u01TLphpwxzt+nqexG5Dm2aRSf6BRrPqcMqsix+cjcWLMZhf2P3TpHkOEZzEPdiywFLr152wplszMAEZoaWcZm9Kf3sFuk7Ldyq7pkn325abIxfToXMgi3dLhF22Mf0WmuTfQ3dj3TsJ/NofImRjPpeIafMv/H/uA7KK0DCKRzIMIof8ftPm5QHyoL3j3a/LAMcFVlG2jDiYTyJ3Gvc2NvTWYnqtFuuL9y2sKlZZx6xBAW/LG4olihHRPLq/2q59Y6Kp/tJ84QFSLfbsCpzqRj5156NPIEeHOF6+94Alg1D5jM94UvTBs39/mMUYTL71hEGNKRuqv5fOiGut5JuZLRIrSfLi1B5w9tz45YU2LV1gQ8y3Dh06PcMDKzSp1o8JmHmI78bR3pwy22Kz87bLHLnJjcA/WXmouAal8WJ1JF0WRASjA=
  template:
    metadata:
      name: ocir-pull
      namespace: production
    type: kubernetes.io/dockerconfigjson
