apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-sqlite
  namespace: production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
