---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-registry-pull
  namespace: sitio-staging
spec:
  encryptedData:
    .dockerconfigjson: AgCmFqytmIuNV/6zSQXQRuS4F5tsJe/RQvmVwojKLqDGBqxRT/MnS4tW1mMy14b4Z05cshJ5/zUEwl3GabcMWQ39rV5OB2DkRiYX+IYLRKj4cdaEc0s5VEP6KnMYoNwHCTtk2pDJBVScNVEiVLIG1GG7NkcPIXkf7cX2ihOfUsDUaYjQEOesBCbxoFdwYnqik6BCYmW2jLf1jEBGlseVqrO+epU9ebfiGDQj6clTLiitex2P3GwdCdXXxVBRKR73afaw16+m1A457zX0z/hHU+spSnjGV1rCr3w7C+0hRm5WGGC4xay6z7UQXveX74YIYGxKLE0TcV4kkV2pUOJ2NucRFUq7lxhIicX1ULEbzYRcWgyQmyWLmgB86agBu7RicNt5Utt2tBMtg1WiT253zUmTvHZL5D+IgwrmSeFJ/Qkd7FINphnxK5jZSST6ho+/VnQ+VOw6CwF1m/L49DYK2VDa3vbsx1nIdhbEFE4ISpL8E9ucsrR5loOrPEjIN+U7WY3LtmkDDPFgrycaqpDckKxixoXJIxbuO3yDvDs5FVuXFiVdmyjJcEHn1KkpLWWvrAfTFr/3wcZbzbGH3Ah+MWBmoSj/IqlvOrUx7po7PFtTbzjEa6pOZ5y6+PTBy2d7JpSGK1aXZRVMioHZ2ndHOO7alKdV7AoglWFeXvHc1txG1CGFmp7NgXR0V1aSB6QU2PxwK06t2WtHuZri0Sud4EVFF5fX5/G8QA706662dsunlT57a2WenCsQOfaanhsfqzGd8Syvhi/sOB09QCQsboJbn71mbbfi+lIfklyEWhWE5EIf4sSJz9d4RgyI8ksjOra/LN0P3mrA2DQwBhN01e/XVoLxS+uu/rVHcP9T7htazbkTQAwoc4styKQYTBR2e30V35Ba8ZBi77p6qazUN6/D/+TWSBfAWmTXjtrjrbQH9TcXaxqc58dNzP4Sw0dh
  template:
    metadata:
      name: docker-registry-pull
      namespace: sitio-staging
    type: kubernetes.io/dockerconfigjson
