---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-registry-pull
  namespace: sitio-staging
spec:
  encryptedData:
    .dockerconfigjson: AgA4cPsKRocYS1DTLNB6xMscjFEQ+oUFqQNkS82vZbm2x7IfjNT9qhdwuW4EQAepR36kVZy35rOye5VmsuGdCZcNVW0uAvsbmd1tlQJYRA7CvMD/i4KuEfl+Tp+qRZAm08OWIVIKR/MUq7ny9l6codrAs35ATOl5FLJqfy72FEWa/uzv9FUViUcHDgNgqmqbbeecmAKobC3NkADdEIWzEuFGiegVeWkTbT+rhZT7+IGx4XGYLussAdYdQjBpYiH0cuY/7UJjY5Yxaz0Qh8lXDvyQFDxwxg8qVROzh1+q7qZVG8BfGdeVWtKurblDpzIunX8757WcPAbS3Tg5XS081oXUrj4hnfDYwvf6yIwLUrmzVZGSQhVkz9L1tR2W0ivNSU3bqAewfdVTzwVbmbpOJ+URDAOOjACkx9LN2ELF0KySiGXvgpJjVbYjA+m/AdSluCgciNV6glOx1ssqmNG9X3bXVPBoJ8+i0BhabMYwdB58OatrlkcoEoMPRsXplFsBk+RFIbdrtSwN1DwVA8RRof8xT8aD2zG/i2Yo7M7/lxbDnpRvIpqpT5NgvyABmGpXf1qLoSgP6h5WX192UhBG52iDiMj+8yGE6YXBHMNi/dlkzEKlgPO+w61GEP1WhEa7dpgMvKQASbuO9cuEanDrC2mMB4TqQhKNZinK0qwvUvjdgj4KUqM22wgdfweEq0XyyJsdr2vjqfJ4YG6f7j6B6SRIsDLKx1bJX+xmi9TcK2leRAoiXBNvAqzD+6eEsqRw3AXImRKhnkxh/qinTCf+TCO/BWoivByn0uJMN4xYzojGURPCwRoBtCcptrjNtVDJEG6HFoWxuU/jOLVhjV236HLkBaTK4/kzgZ/vDz2nghxk0dBdqklazYVJ3J0DLwIJ2uMyz7eF8OILD/nG+NxmmnSPf42+X2/y2VZdKIf3wgTpIuIUW6EhsisSEP9jyio=
  template:
    metadata:
      name: docker-registry-pull
      namespace: sitio-staging
    type: kubernetes.io/dockerconfigjson
