replicaCount: 1

nfs:
  server: 10.96.0.100
  path: /exports

storageClass:
  create: true
  defaultClass: false
  name: nfs-client
  accessModes:
    - ReadWriteOnce
  reclaimPolicy: Retain
  archiveOnDelete: true

resources:
  requests:
    cpu: 50m
    memory: 64Mi

