---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCHjP9VAC1UPcxZe9sBkuiThaxnZ/8UZlY00oeDLeJONB+aSr4hLJYNnqXRCFUkZOJSN/hLMhAhDB7/CXkB6TLqFlKlJen/hgx62DnSnCSIvhzpGZXOFQ5m+ElcUAgUEaMMBq+ck873Nnw+vhsC3JM6XXW4yCl+vOMqJCpyQET74xFMXQAEcnJhlwNHnkSvJiKI+HPoQ+ZAlHQ9bv2UbUFR8Y9bBb+8hG7mYVSheR5fLxcKYbgu4ClnEey9jdmqtULMvE4SxWCiCoN7ADhaefNgy8rXT4sCmhKI/Jg5xg+dCi81tSnnGZVF9GiYuRz7pgyxd+EYgLvYgeTautk6A730yKZ98RRCUucgSP12keKtQ0/zgqOk/Rr/7pSa5h6D3KCP9d1H+XqyTn+/n1K+WDQT+aY2Cx2LVEV1YlPyMeIwdOMuFaGH0s5kM9ppv4aJcy2K4bQZzR4m166jWUm4zA2pV78WrOlwcU0if6LDoN6RoAQVr1Lx6qWu+MW8PKD3Aoc/ffPnkqAKm/8xgKlbaZMCM1i2bqXmuPbfsKDZAFFXEXrIYTc/M/chxh9TWboiIl5pCu9TK28e6bqwkWL4CeVvC8g7Eezgk3kKDep3l6vHMVfwqcgp2LvHfe6yqXue94+WsWiO58/2vKclH47cwsbgVbjXhVos+PZ5a9tfgh26dYxHZQttRF830oUnI7N25BwLDwpJX7t9sWjRaMjZekCH0g==
    client_secret: AgCVOqDBxM5xw+nHFhz+nuG/PN8eKGF1EIwOkKEf8ZNqms/r/oNKDuUraL5lGCp84jze3LiAej2Zf/JDuuAGipCDq3kzQ5cGyKZ1xiNb+rZt48hoMZv6nA5Tc0a2UIAIr81a78A8nVPPkGeAUAebtIgerf6WPLRH2c0YrzcwmDpk8RaiucuPnOtH2/JC0dhTOtY7TrG83uAjOHdJxAAiLZCyO0OdFAnimkC9jNpgZSIu+AmkLo55BUSjZ2C2Ftn//zVoF4gbaSN8SXJ8+ARKmNzrJoAyWw7TGeHySthnzoNtP/604eZCibZMiRuTdILGDb7IdVmXN9spdWzCksaBxqQY40Dh6JpZKDzCdpXkkGe13JEXA+rcw85Pr8dWc0PC0whEx0n/w/Yoij4z+uSlPNUvWHUCBhYF042PHVT+8tHBPv/Hd4MjG6pZ+QgFAANk6RVlsLqHO4IpvwILTfK+QYEFPTI1Nc11onvX15EyivX71tohH2hU4sHd6JEA9/606trrJDKn/8+ca9sITf0NxsoNxk2CzmQ+2Yql5sXAjp5uY2aHOFfJYVfFHhpDc4l4O29E/IMyUu1lmzRdihpcwnJ0mG0PuwdhYken9wLTns4BdELhGJVZF1JoHCxdLUTftxXIFrTcsEgxqbBPgKki627lB+S67huAWoyksPa7LFkR05F+ckQ1dAn3jMGF6ITY+n/GP/QXgKGOIhZvVbzmEJDh6rRy+8DAnPVRFzi70pI0wwaz1gc/gelKO8y5F3oeNK2KX6dQAcggj9cTWBtVK7Rn
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
