apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sitio-staging-postgres-data
  namespace: sitio-staging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client

