---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-secret-key
  namespace: harbor
spec:
  encryptedData:
    secretKey: AgB6mwXYjI9KMheXO3bGBu988SXfeX1jFrKWA20srux9ZN/tvL7RGx7ldRPll8cbuVkW2GxtR6eGTAGWfLZPd/O9ixDpMg1ymCjjzUh1MAX861wCoLdMpZS9UT/CPjZ3jCECHkcm/uk3qKNJbEkaV0idmuBo/px77jRQZNjRrVAoqrgps9UEcUq2MwJejdE8D293f+yzg6LJ9VZcJqOAN+hvTvFfvchmnqQGC3uRufiPlsyFG9GDQgs6MJzJh8Zb9L9WSjmIlwlyd3ldMu+g1tn8EHbd0q3wEVgYOcQU437uFER5H43itljVEZZKf94P8bLC1SLZ/WweFolVtBRucQG0ccdHOClXGu1M1wfa9TxVC+DevIUY2taxAw5/7saPJ/lETqFP2ZFnWsXEEQG9bD4dHPn9efCCYFsOgc/ccvRRBpAy036fpHnjY1FVcR0QPm/eQaDG2c6x/oa6ddkNwyQituDZEhjHmjunoWaLuEtGvKBXjddl/q9R+VlIicRQXO8xNReQCIuo0XHhEohdabC039rWgIX28gbEDT2cNbeWaYhs+YVvvhcVl0zq5Ji/vYgQwi5c+kGZRVH7HrnhpsZY1jcJSpTYgjFrQIY4D8N0j2CFv04HgPs9BvnIII0AkLyz8UkgzO//51oXRXfGxFA49Cp3M0p/VpoDteyrkXk7ZNvxgoqsbfyRuiBHN6gLdxSoaj0X4yLTSq02Yd6AQKPm
  template:
    metadata:
      name: harbor-secret-key
      namespace: harbor
