---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-password
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgCqLODfmcFKMuoF6csZ2G7HjBXrU0XEK+ourpRJGIdQSys3H4Cx0dFqqMh83/5RPJXYLy82fIF7D1uu3NLAE/mRbImJZ2HKyBJvfb5PIPeAHn4YXqqfShNt1rv4t6Q7JojxKG9DXCjp2l+ktMGl37IIoVkJWOcaXqDoH16vtLDJ/kbUqa592CM7i2Ih3tjQ3jWpJr2Db3yOk21mIeG7ynNAF3wXqOSCQV/uMNr8fZA7fLVNwxioxnudd0xLa74d8G5bWVzNkB60epcZL5Vy8jSRI6V/nXJ+4WQwU4ueDzu8j89ubo1OCBLzroyP0yf54UJmw2Ves1n10JTb1aQOi8plgkgFQNlrC1MTFIknanQaKkBbX8v152KNwUJ8RnkOrH89yPsjydB6q/9FshqQ1wA/k36FjjQ0jrAp3kNBO54IAymO0JgaatsAunP07kdIqFAUfsy/dyonPaLPAzb2F+OYLcAIMOAbXf1sRC/6k7TaWlG553/b/LhGGHfaPzbe+RAsu9SF4EmOSJ3FFpIVmg2ueW/9oQZqsGCS3BNWsrHiIoQSxX9FXLcTvCB9PmVNx8ERNQX/4ya8NSvqZipqmxslZt/D0HcY+bD8H6jje9fe2jJBMJqVspBHDGCuhQ4wW6i4I7jK39UFVimwEYvOf9C4TXncdg5qelIwKoawr/zlM+3cWu3/KdPhSNoqIKjBtYp8WqSjvfeAwuRd4espPfZxj52iY6/e6Zi08e9MK++iRQ==
  template:
    metadata:
      name: harbor-admin-password
      namespace: harbor
