---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocir-pull
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgByIJYrwFkdv1Sgzlk0CJJonKcVppLiayUrW1B0VYA4xu+mnOYgUHv19qCw4uvC0hlkvGJOZK1Q0Q3y9wEAyd1ViKVCzJY+MatsoNMEWY975tnhLTpPSsWPNt3o7V4mMqRrWTphpGpEibCkoGL0SwUPUatqniQEPnIun5u2/JjIXS8L50T5BurHuFivt7cZT3TwwFtQH/LaM7Xu623eUUONC3a/LsQKOXDXGrDFykRUW6umug4uKbngCYG1d4OU6KF+peJ5SSPAdeWfHw+9KFQVLlejNukoQx9RdB8+BeP9oCElE0NZNH342XyVA3NIQ33b40BYwUG1AeN+MuVjyZmWfji6vjHJaZa4HqLAeWV1k3l0R+Vf+oOiIP7BA40HkkmZkh51mC88iwGrPBMrnTkyBm0oHwfR10sgaLz2nuKm3VVNwW6dLAd3DAr/Fq0tTmiK41aVc6YAEXldaiil9esL0xxWHhxID752uYYDeTsq2k+oKjMicKrseOaFAzCmiC2GrTqJy8GislPLR0UcGl4CuXWqWgN8/sQyRvLoJUV2pezwQv+GgFsWNmAmgOyokwGyFrCNnwdEjqoE1drH7oNPWUDBssrbAcpFplzku0XL7ZL6qif3+QXI+hLjPfRD6Ol7bVnLenrEybRdoIHmnbW2ULqitwz5jkB4406UUxmWyX41E+wDcwlpeWNRdA0cB2N6YG9C4/+Oi1ZdUKA/EzMi8Qgr7dc31BwICYbB+Bg3swqxs5CuKkh83cWzi8fZLWZHIJajJricSHfHKDSNBGdzWskxtldKJknJ3XC/oXG9XcaEY0GsP8aqlPomh7O9oKp0W/QAGoUdW+F4svW2mtGSSF9uK0ddejyjpkSSzi5ayfdd7Qv6yRhEdYEGBIed1yKbPKCX4QNcTY0lbq1sf9eyFP02luYR8RYBd8DSejhYoihU+4TEOSgKRcZQ3DvpFHm1qm3bSBIr4yXXdfUY0vi5KIDIdNyzYhn4kr3Ybu5ueF4VuzVYabc812XoZfrvFBrduCPl9saqKvhB3fXVngP3tIZWgXy7DYnr6PRO2SjQVYol7OrTmgO0ionTCqhSPtm5iIzztMNZCcQi89b+vDPzub3cjhWHb3edH8//Jz45SWh3lf5XUSR4R9t48iv8C93eku9IgMkI/kze/HIZ0Yi81C6OrvbELapNN0DfGOTlCJV0mYMOrCj9qI6V6YFQ2lvCO4HhaMAEqnjXJJyxyv4trnw1m0b4hRlWfE4u31Fg5lis/X1SOEbk1QxD9YGubP8bvR+ZhL0JyeIhSf9sU+dYxXhX8mOlS/IKHf3lmagZpTC3YsL45swk/APdERvFv/YopvS58Uxo2UjpKCE=
  template:
    metadata:
      name: ocir-pull
      namespace: staging
    type: kubernetes.io/dockerconfigjson
