apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: rustfs
  sources:
    - repoURL: https://charts.rustfs.com
      chart: rustfs
      targetRevision: "0.0.86"
      helm:
        releaseName: rustfs
        valueFiles:
          - $values/charts/rustfs-values.yaml
    - repoURL: https://github.com/artieeez/artr-gitops
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/artieeez/artr-gitops
      targetRevision: HEAD
      path: rustfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
