apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-tls-rbac
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/artieeez/artr-gitops
    targetRevision: HEAD
    path: infrastructure/traefik-tls-rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
