---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ddia-labs-secrets
  namespace: staging
spec:
  encryptedData:
    SECRET_KEY_BASE: AgB0HnzXvUgDFYY60M1p6KU3jdhiLjpivtgt+mM15k4ehXdqOtLr+60Gku6Lmih4kb0QbbblO0tZHDIsGxld5sgaFeCjCUJ64HxdSwjimRVkeu5t+6pK5qhkA+xABWU4GyRAGnaf76MRv+RosIyzd769eDGXwY/rs0dpINxGtopUtV1nkHg/qHOUD/8TCG6+vOnlkwKHYmiU3L3B1FcRKlPiDB2ESgeO/nn5T9S6Omis8Z2zY+i7md7zra3enWncNpnS9A2kUaJGTdkdtQhhXqmPyZ8V09UlLD+aG+5yK9dDVFWUOynfCmHBl6daMxFgzGYMOjcQtfdNMoZYLBCvPq4kaJxMvt+xuzL3WIh8u0trBLc7wVSSocURCZnENpcciTxOysJTxWS5FKYIGcBRHh3TVuSKfAWtZph01ECLpxzQrh18E51vclW1m5jY4t9LlR9kgkar33TZ5BufZMmvvrcTaSy4uHRdYS4UDJtYe+jWMXaWl+P+RG534dRXjxnKSFxb75elu68dsicrBUQz3kpBtj20c6+WM/fE0LXmdGowo+JN3AQl5d13GqyZ6EjyMOqMvYeEJSaeENe+Z98HSS57g2/PiEYQMRuw+pfsYIj8I9h73a7zXQovhpRsjNhQ0l+DYW7xEVYNULdwAQ65EzF2om9S4LDp4EtqI2aw6/1yaSIJ3eG/xXHnLSY/N4399MiGV3C/OblXEREBlSufsmmtIunO/uKjWDJmWBcLCErhc2KynybtTLglH9GzTEVR9pxrjlX9MQcxFgnPRV9CRZjf3S3HmDUJqmZweS5uVGXelOs3tWwyokSMLw09aaJdSMWclouBGjbUjtpp7dxlsuZPurdHjMwhgFY6gjo2cGmJng==
  template:
    metadata:
      name: ddia-labs-secrets
      namespace: staging
