---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-credentials
  namespace: platform
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgBZbm6DeQrBDnPlm3GiWGoVm74DQS9mgSeLgDC7v//mf29pYbpl+LmtEbl0vOkaFZCDMVpP5E6jJfYkxsOengXVWDd+9eRUl18eTgoqUUVan6cfEqrVwVYUx6ea8JNqi9s+3U7b9jALI5ufVU9eWD6WiJRKRnT9wG1haMCce8fb+sH4WYLgk+nbWr9rCghqeGGo0k+P3JRr0LvGxWfnavpXkB3Uyav+a+18uGtNu1QTJPJ5ehocck5UX2L999OGEZb3snc0jMWfk30mjwV+W2sFwpCdqgjomQaZR53LwoaNeGqbbKYm7dhVKvFLVsrIqiySt31GUNpaaLLgA5gJvvcGC7neJP1gFJZ7MxtRawekVvWN23f9VWxR37B3lm4hyOUW0g5AgkZzk/zpNEeBf9QBnH54LSDzu8VK6WNJnhCcetBLzmOcIRX+boxt5IZ/4ctuHnMS1AtFWX4e44DH5+HOw3beS2eMNUuywODhF/MLPahEyzG+cAaC/qQamZyknB3MWd11ZixCRfPVc/CV1sXOAEMYXEmrL8dPobOM+jVUU4ZoGheB6R6Gpl5PvrkFZWB9/QSG+kHnfPEygZ609IeCv/NpNoI9DDXz5/jYlBWcgRqPSdtPBYftMrMKQbsaUkV4BK2SDRhqcx3lnxksvVK5AmSUpSJThrSoSlfoPPvSDlHiAw1QxRSBvlbM2nXNXsyJ5r+fHQ==
    RUSTFS_SECRET_KEY: AgCKvZ10VXL/FLZtrl2E8m5LGqK6uqtYfp3zRxoPLIu2wIHFoiAgOjixnjmD9Xjc9oXnWmsDsjP4hBdN4WkppXLPuaNdWoHwaDmx1IKpg8x4XqruCGLJdNcA9pwa3AqAI2cCdFo+ReVkcqcMO9iAZGAPAspfBNP6jJIXoHmjBj1e7LDkArEhkMVbIs1NTHBLNTm2AI7i9/meyS1w2epQcIX8YzBDHbHgu+m62SIgH0fy8D2eohbK/MiImWp33k+MR9MW+LBf+RDY/F1ij5PK4LCw4UaqAcOfVL4E9AZlAnOoVDIMVdQocThLa+d6f72mDWX7jEbhxBuXAgbTy6UZsszf5uOvhJvrIqrPKY6QbK4P6m2gmI+rcGYUkyB58q6MiYK14MpQBYcTItqP4Ea0Q2yfPQkopJb7k3U9TX/gKMtzSXZOJc9b5ql5w+EGpiFjCQ8QYJxz96q3lIGU0a9hY9tLVEz7PPGg/CKCNiB76dpRMu0wRk9rRn34Qf4OiGDpJJyXQXXnbM5ttr8pxzr2jTn/jauE/XACC16Kr7oJXfxztl3JRG7quQSbH+byPWEIRNjoqpXwQTmCB3BX87CNGpl06jjoAtJqPmZkG/eHbnnmD7QBGIUizSUxkninlDcTaxBT3qH4BSBa4q7WGT/qTOhyjn2bUCNskcPWzpQ4J31W9tFsLhvmlRYVxfyr3+Hq1PjFJjyXjOtEDV/1NfgT99o56LFVTjCqyZRzOuPLYnh7AQ==
  template:
    metadata:
      name: rustfs-credentials
      namespace: platform
