---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-credentials
  namespace: platform
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgCi94E4/1QcLWIpj3OoWJZzaE65aQHhmbndmrr1LBG6TFAnw4qNXJbhBaqusfYz0F+QkIc3zEf9qWFF4ZdE9IA4aoiN+mFejIRdIGfRH2LZQv9m+PeYat4nXhoEU4Uy+UbvUoQ9HFZtFHgnJX/gY7hHybsgBK5lLznlj9XJc0gGPMvwh7ILRoxM35h72Df03wT0iboT0dqrAcbzPKXGo9iUckyNIIuayaHpN1FCuPYyCkUns+JpEsDaA/P43FhFlZpCyXEnbt/MahejCPjbt+it6/qsBe2nhioKvS/9bfNcH8ieBUHbq7BMwjBPdpqcifqlGY8gX1xfy1JKt8F4N3Nu7OprB+oyXZU/sN/FPz08PZohpnA87fOTSq/pKgmdNgwRHqye4QRR5knUj2TYmlJEDYx82aPUshtgGjY7cfgOnQWwIaM/RoBAZpiSUG5/1CW+8QY5JRYa4tP/Pzt4r8izj5SEUrh/O6Ugu+jTg6YiWG9kSobwkMAgmiZtM1DLbEOZe0VxWA9FW07tm414Pu4CQwf9+a5/BzVG3oPfbEkJAJR8y7MDNLcT/YWHxcBQzL9SR68DR74AmrA3BncoET0WNc1ywBDsCOnV5jp8y0WK7CtxKw9/vkfFim4aC6tdlIF+DhuolwVbX5LQmCT8p4vtQz6UmTOfeHWNAJ1gs/QUDDeebasHcKByoAD8XQwPwbkCNWLA/Q==
    RUSTFS_SECRET_KEY: AgAI9bCYN01qyAYWEdjxQyimMOLveYq4wcf7m2W9VDt1lqCz+VRm87t6Ys8uIs51c7hx1iwBMl5PVIUB5tdsDSSdeLOeawaiVGjZeHnZD/06BYkEPQEB5W8MMAbr3cHy1tuIt17fA8WQSaRgFflTEgCNze2c5ejmdITNUmrufAqaVf9hMEQceoyuLIxTcd3t6w57A8IfB9eax31TFbrGOBWoGIFzKXlMFV9J59Bt3KxX6R/vDwu2O1meniYErjgTbKnYA0VSoToI9dK9vg4+lRA55GUGdtj7ziC+FjeovF90O6Uwp2Ln7KFz36PlIrOE9KiV3dK44UC9EG518LOvpUTZdUPutRCXAJLLE4R6pnORWfM/7X12t7Y74z7PKEuAH3AWMZ6dSqAhFF1Uucu90nhZvzOZFY9EWmFPlyV5NSuE3HDfGcKeIdu8lGmQfIixZzOyyyWbZ5b2FA0f6eHUw1WdccrH8q5jp0f3mdWCnXHqoyKLjC8MAWV3GnD4N3tTgwEzIB1qMT2cnzWUNLeLafWG/0VqrzFAqaGR8ZLjzfaq4VBRRj4XKS65WytZwUMuTD8avCm54wb7MCVHMiKetnGQ6nI+mx9eCntsMaH1TO+Tar0ZEtqoVwIz31pYDjt35KC/J++ZQuHoEi8c67ogx2fgsZ9hDAqXsLor4yjo1PcncgeT8UyUd89mdhu2+KQXarNpXzuz+Vjcb/jVxxReGxwwhUc5A7z7m4tBxPyvf2sK2w==
  template:
    metadata:
      name: rustfs-credentials
      namespace: platform
