apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staging-postgres-data
  namespace: staging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: staging-postgres-pv
  storageClassName: ""        # must match PV

