---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
spec:
  encryptedData:
    slack-api-url: AgAS3Af/DylsUwuScEl4DyNOSjkRkng8TfxrBGcYYJ/kcO2XuYsRz4awI2QMXOHezRKJSi5gZe3qPWN2EB8a9dAnh1ANu5YEBQRfod8Y1Ul6vbHWT5i/Nk+fumQ/fYjG7YnBuEWZhjISga7+3Nw5VWX5JR4XW9kyT3gItbjRjnbayTFrFuG+e/VC9AawGXTvs6VPfnk5RTxWdclEuC13WE8lQQylHzZ/jFcpThKxGf/n8PyHGUljFF/ifwhchgkMUWysIqOJ8sv1tigKktW849bG8QKX3P2bidKz/6G/j78ASrhG/9QeOCPzilM+ael1b2XVCdy+go9gtQnqOK8KzgLyhYf9SJHer99fkTD1fXyjVP5Ar2xOxFYVhLseTv28K6Q+CgtgajA0JeRsyoBM694xa3QvwwibsX5STHvKXRohOHmYJFGY7IzdWYoHXuIIsshCtz5iL4ng4s5lJaADXQl3T6ULLzrAGkdlwtGF+hlJjwSlhFjSsIQcz11pemsU8hNQlDx6Wyht0K91XIWMQV6pGZaV1WBawJcvbx/c5j4q5QGChyOuG4rCYOtXwE+grO5oYJdRRPBARVqMGo3MxyFGQj7DOggmR4XFwrEnzHuzcY0fiv/HCUYz3/D7uCuFWRRS3piZkbQbqwbmL1G95QNcTI6JYspqgD8xVy7L6MkTuSZI6ZgPCwU99GNw/R89o3np1rHqUnmYBJE6GbCgqztjf8JI70JjW+AcZfOq3RXaLyIpg6L0dhIHqNw6lBKejqWM4xYVZU3+mUHOpreTkpF76kSb0mjgRYTo4m+kEhEw1E4=
  template:
    metadata:
      name: alertmanager-slack-webhook
      namespace: monitoring
