---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCNILhl61HDy9SEophVpI5cBMS0akT9P8m7VG729fcjiT/0NWxkKhsqr+qOpgVk3KYUdQHWF880rN+ekah7GopnBH2tOOxRRQs2nxB3Cp9gB0Fnt5PfIcl1+VeBApsE7PkNxqRXMZ9ZeNoKliIX3IiYZOG/qNURRWOkCOoXx99M3/MzZKEnD3l9YvbGpc65QK8M+Mu3N0QsDIi4IvquXOgT6lXMLsVenud+GtdeN7PnqbkuJbtEJDdE7yBIE41P9LObz1d06AGnx7JnVfRZcVVhQ7oMgrveQu8OxCXcyOH5mUzJuQugpqTOvvkHdiZxUV8A8iqY4wPwKysuthFcH0l0YN8+LNDgUjQCG7WjdGnp2uEhbE1YVhYL+VuKMZhpk/VGyNzdYx8Nd3luu2jMc+0Ld8IanvzxPmz0k6F2mZHl144aUZRFFq/yko5TANvD0LknZyqXT1RxcH6ys035O0fmKPyXwhddwxe/JKrbvgUaVXU8p+Yv8HMINnwUnn5zKow/WPy3trhbdqkqB+JfXJ4Tzfc68HLQHwMJ55Dp8+F0FEAxJpPnjnHicIogpDWsREpcjUSQFLXolDdWydqwBhDevT+KCVSI3D1h6YjmT+2leY/FhwXx9aECGg+U5eDwAVzCcugHIdszAuSG7fJEWJ02bpXt/z47XPwbIYp88G9EsoQhnplwHDiEUqJSrPqZ8aFi9u8OCioiVNloqUvpfUJJB2/vDJwqsOdbVACL+uKjjg==
    admin-user: AgAGUgx2mWWqBX8kI+jN3Yxo9dnx5AE6oS7uERzySc8l/BVMG+84yF8Y2q7AnRL+NM2Hi7UMPtnlAPNbwGhGPqapMFZTuGcfqbVDcMYWWYBPniLJ4ozbLVBPIJu9JHY1mWLPY1YgsoHQhmj1sdBC1GtRfd6+ksli0P/xgP2tAQOsU5ZlcvvJEzZoOUnMXZZGzgfATLdMSeMHjlbnhEyO89NhkKS2ln+IA8S1XexY37sfhV8/SlyWJPsO0Lp8Te9rWT48WBl9I4Gzhh3PpkD55n5fgKXXi3McBk1r6ufgqdwVkccyseyHX0yvg6tnjtzQ/5GVGmcu9QVmmICTcghKrGpyjv3mgQ71piz6UJFi/+T72ReMPLjnZYgtXNCI1N8ONRF20kAhCATosbbwHnZsfOJTXIitbhhiS2sV70mYiq9K41JmE/wYMCGfxcshUOtOHPMgk7NxuoNTiBl4vYC91fOfQroFKDGdH7FFvRhGxMhMKlTlpJ0uYsZsyFeZTbYoSlr2pj/cwh6JFIC7IsE2Qh1i5dQ0Co/eb9IKTNE2cJX5TB6mWj2c+pdIT9zCAs/H5i9ujZw189RZDihWS2KY+d/HB0Njh94oxcicpdHsgarrH4C1AlIssrsfJvChPX7mT+u/xyxiCZsiMxdNS0CwMP5dx8F8QKRDjlXYWmP1lkwEgx1ZDtyJK41rQQ9SLcd+Hf+N5QvdhA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
