{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "grafana-oidc-secret",
    "namespace": "monitoring"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "grafana-oidc-secret",
        "namespace": "monitoring"
      }
    },
    "encryptedData": {
      "GF_AUTH_GENERIC_OAUTH_CLIENT_ID": "AgBoRGmFw6UYHcRs3U3zSqGLAtgoMoittwqYtUS5Df1t0AknmtTgXBIWa4D91zZhaZfrfunV3yck7svlbjtEVmvKYw2PQqsx09cfCp87gdzgbU9cpnUT70GVpxP7C16BglTUAdbKWH7JN901MFzE7HavanbV1aqwyzleUeZjMg7SPKz3thdkWbeDia50Ak7S53alu5XGpyVkcxdNFb9rMo9giODaIF+EJ3Q8hZW+xenzKYD/4LdbhavoKq76HyObng3EST9mDifml1DVUt6b0+n3HJL0+i9hFT77mHsz3fmsg3O5nEoqqg1oBqmP1V6Uva9bBJwsQ+wJ6yMla7Kr+s/SUUarivxvY9UvqMo1QJVY6kBBja+FZ3GiVaSldfIk81/Gg7vufPpmsnE1nkzMImtvaHY+yFlDXngEP9DpGnGfkSYj2w3bTGb3Q7Sf0DdjbCCESC4oZs2bKxKuB4ZVrwP4C5T8MiFDEtqjWFjBg1W59Qx8b2pUyRut55tiqm9ThbJn5Hy6W/Rwa2R14fzisYHBCk/JF7c0g/uF0R2rSV/ERfPwN3kJeud0X0xchWyi0j1K85WrgbgcygQrT2bEGR0givfwbntz5bRGFZfRldp897QS1lTQesNKGt5C3vhYGOJF7m+oZCT/uzSQYAzapa0mfun9G6RBu3aNNJ+Gfpb1o85jFBKn1RUteMeAjZYdXnmj/vGXiwYVveEEBEgED/xeKgJKdvXp+TTT2WLwN1K/zvhM0Bg=",
      "GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET": "AgBFLT63kZaONhjlcOJeq/KqZUXxK+GLL2HPLJc/L2PJtytK0rUhgF0k6VeqRcY2PZD6AEyMzitAODeWbfxSpF5ZsTCkWT67WIeo4tTgxkqTQbeMgvh2GbJkfaHxa2WE/C9H1PhugQUNCKKIefMbj8Tw1Chd16foMK7KJu78T3GypwMq3RvKoefN0ZogZzs0aYFyUBsqsxPzr84FiShppuxjgO/axK0ciXt/t7yOf705pJKXvLl38DRy4D54EsU9fZfhADc5UxfcYYELPGDDNLQQoceywSZj6Cf2OEHcNZAocuCAA/ks58tgZfjTRocbwYgjwXfMr9SE5GCso6LRWsAMZa/NIRlYj+rPk+fLsKNJ4TI96WVPSTOGZnOho0z/ts6ywk0kSOYlpjW4gl3A1SlDYd8DfzVARdl197TCvJ16hsEc8J5EeXQcgCYVm9E3UPedVbZf/g5optouSkht3bvBSJbttdJV38Ncfm8ZiC5YU82b7OnEO9Ai+kmJFONlfcXptonnGE+JdPQ6vJQQKmjdCDbRsBdYY+9sufYimljc0qGJLZzXpPGWAbEhqqvcPtfuUT7176ov4j+u3sHSsAVgemtpbdwsVxIyatO0D+rBbKz3storCVvKw6lcGx1FuRV+rWqzMyZHI2i51jT2j1HZVrCGq9ITl13PQZPIdHnN3DRQ7EdkQ5qdIMrFN+EleWWCeAV5ZSUB5zJhKayzUX2hx9KaZfgV7kYzepNHute4NA=="
    }
  }
}
