---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sitio-rails-secrets
  namespace: sitio-production
spec:
  encryptedData:
    RAILS_MASTER_KEY: AgCLscMrjD8F4m5F3sqSaxY5NoVcfhhi1XM7PwncO3lZIWj9u0EFTN7eP4mVNY4J7oSyetsTYMDzmfqFiSQ0PfHVcJT3Xq7LLoOMqEX3eJt4hH3Ty/lthCsQ1VJdB3ut/OFW+gW07nLwphKE/WyQBw1lIwe42eZG9sEIpTBSKVMyyqxjl8Swob1Mi5v8hC9gKEicoW6d5byOQZSVHjH6ZShkvcvdtxnDQs3gcxgmYYSPz5OlA/f09P6H5D8ufq6PWebZmt/DSXSIPX0pIEPyUNW8IOzupuGUZdgLHY5bfY6gGk775QDpXtFX8GIalBCS1JZzBW4iw4O8hqRtDsZwJJs2E8PwTV6rDWeuajwwqjisGcAkOJaxPkilGmHH4t+tV8qSmCYmlCxP6sQR6DYdXXyaIX9A4pCEMPJcWmnkX8YlIuEulxwFUhF2AOwtk97jhLKcd3b7Wl8T4TUuoX/bZE7B5hRplH7ioCfecv6WSFyM3OoE9E+gwJckOqxLuZ1zlsNMRSpUL2xWY1xg0YgmcdsX0pM4ahwFT5v4fpYAfr/NpLyX66dFt5ltdoTvyt828q4M2CJzZKFmOGKbDh/kRXp0LI/D0Uph1JK+n2gowrdy9r+wn19fIPuR8yonUltSeqhTRvScy6JWDI74BwAooKXLNrtkEhViecMEhG4VWgZceX3A6yXIDPFqt+kqGyUNnMg/VAW5FLK+pjOs839FjUKRYBHOTwSfHJ7YkVOH8PDp6w==
  template:
    metadata:
      name: sitio-rails-secrets
      namespace: sitio-production
    type: Opaque
