---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-htpasswd
  namespace: platform
spec:
  encryptedData:
    htpasswd: AgBXJQukr3JBD8Xq1H9S2iX7fnrDcb7ciur8xtvpok0ALYRO3G/rYAbx4ql66bBgRyGylHyTeS8rDop2rZX6gbjOBYeoetQhfTSadCZ5ALLbBLe+4aeTTkUrl4SQj1T4Sr+HI+QYHcRFtMLbn4L5DfhjDn0dkGThcJ5NMM1ctP2mfqeRUDe48fB93vOc1OHCZ/gRG73hM31hA/vBCeve2OTqJaJ/TxkiSKMgZGotX4QK4+SKri1AcXkWvSeN5jUwNn4vpmP4M4OBTxXwAyLntxjZRtBp990unjrLcNNX7b/CCth52MCDLcsbOalYHzb1eVELcvwf8oKbqZUUC/6DkNCHeJa5ccqOavqUPPxc+X27wkTt76taHxXDV38BPB4kPX4Ue51g8CS9E7POXg9jSzAT7ljD3slq5jSw3o/AZAEWyw40jYMY8lab4bt3DjiH+tutMgOiy3JyB5Fa8o5VEsyx9kvcQbIevKg0Xt9Ofhz9si17z56tNw86yfg+uPUfWmX73ONLOf9agWrnO/BTyytQA5vsAcl+DF+rqg0KWYgEbellnLSwABcX6kl40EX2eiaRW/TsN9yhn94i3Hu5Prag2tdRGqUKKEOQeZE7hvF/M9kzCAAhXFMoePy3zQIg6tg7sPfiiLUfLrRJnA+3+aSM+COr/xUlqq/uGWvmPqSg0ySyq4Xvc8h+tyqA93c2FZP2nCBQ52WRHMHly6vcXAS6JZoTYwkq/D9wfa7uUKmNKXFgS0kPXTWBt+prMUZr0Lcg0yqR/WCiy2hUCWiz6wL+32WJzw==
  template:
    metadata:
      name: registry-htpasswd
      namespace: platform
