---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCITnJmojG0l7XM3G1fR8lV4C9v7doRiiHH9MVWxRdsdURntelrEtWEBPPT09ztlF0wz+DzJNajIiR7f+Tg0GkByCCT2CdJJ6mPqprq+/KxR6M5koWxbLBi1Uz5TsFg/K6isa3qTvGOHTZZCrNwbETre2/rOdtTeWSCIx2Yp628MbaEfBi85hPaL4faCPyzUS+Y9vmsOzvwl9YbxOBp/rBgLEl39mpK9bDATwj+3GYMSLLULlb5mVTXbZ7K/GwMQE1a7ivD4BZBnTFpnqZgziLSVMgpk2ClJd0tVdcbXYR0S/bAYlJp+yZb+03eDO3q87f6V1cBAhRgLdIWp3RqtpM1nJ3Ph+5/wgy195Ewg1ml78tCzVtW9xr1QxOIsLp4BaAMz1aX57WqOEpViKhlrZN7xxeAWSs49+0Va6WDC3H5tGurksdo+0ZUrtpiSV11oQMvFqO6oYZkXocM4nS8UGs+YgOIMIg8D3n7yl/sCCZNbhwwTsg0j7SKxBSuUxXo8O6bqfJ5t7Ck592qCQJJa6jojL0W7NZz04/h44EqpBfkJPNcpfnUE/9DkSguBFuvG7qKWQ6dncFebAt/cW++h8Pm6loXjR82S5sEwIpIQBTDi9qEAfQ+xbakkV3a7kU/h/Y+9CAvPeliAgU+MGTSu3vU+iT6aMNlGkQQ7SCvirkSe6B4SsA7CtSV05X+xAVF9jyMyaM3rWcEAmfrxbNhLGrqTDYByodugBT7HuUEvckVI7J/PdJ/NRQW
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
