---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAHK7mYQ+c7+O7H2Rn2KsUcsrnzznUejfqh18fw4v9btRLJVLtWop7NRVyX/5xudJTjUYVrLolFDNsenbBftXJriR5mh5b2tyOYR7NBfK14vD6GhQkWfKma9yQJYOBhVdF0SuArdyAvNeDSa8f/Z/P63Pe1+Jjy7Ze6s00JR+9MQU/+yPPU5u3duuJNGgu/EU03g377FPLpegeOSrFKoKrqZJexGhSibvNrf1ZceExyihrLPIQnpdSVVbDzdigFBueTYXxuFG82Nf04ruwkJavguP7o5tCCkJsx8eBeVpWLAsq+RG7CETJ99Uq7NhHuo/ztzCveKI3IGjKwl4Y/V9ZxIJ7znuPrwK1d/+DnyEeJYZbtKQtTiFoJa/MRPBVkLMRU39IOiV9oF8ZgiU+OW2ImdmX2J7BSgp0+QWy9wNQxcGh0InstMp1Tq1ffC8PJODgmHB0MBF8io+hS7+6jqPV58qlLMVWp9s19gI6A2GvzHug5BDQPEISsVGnY5+GqmbY88+4p5PNJf9VcDOCBh4YAb+T+fyvcuuxRWjEoEdVJ7Z1tJlgLyupp1nhhGIKeC5a2rgRNE/SfIQGdoCsbbUtLSQB88dxUBt7CflU4uydyOX5Q3lsDcapBC5WdCFQf9qEf2WHmYr0/1I64dXFfmZGWgXeeHFg/ZhKbFVJrgskakfBtmx3ZgsFGz2Yt/jqXUfDWSTi14EgpKa95dLwmAw+GIa9GYvKiCgrvBrI/yLaSJFtbcSEaS+Lo
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
