---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCEk0L4ZMSj4WdcKGBnTX6n8WeYrMY5el+RSovTJu+zQXEB6H8K4+L8LTFDTd8FXqcLa8nT8tpdGXmQR74WgM0PteqtJK5YMQ1sZhOcpAVKw+6IgVBEkvbWe14TLADU1ZZdzI6DBo2gVdfXHMivmnWIhTw+Y5nA0fYmfPK+dw1JvoKusroiPHyDId2Iz/WdfykzxsFUC1okXuvj9CjHOdi37TK9MPJTzzDS+fUtca+B21+cLQ0oM8V0yzsLTfglp0sVQgUlkaAokYtOs3ou0MdcktI/DCV2GNJKSpQ9IXAWdYHUWxyOKiZOe1CJS5dMav831CU1J4U9O0TdhGXpb9wl4Aw5gk8LNyQr7vSL2OEovBgvwyGm6J3ZBqERoFNdzUzyc/MguwqKJWe0AjxcnXZbIAYIh/CIx3wklj4qAo532OmoAi91p+n89mwo6tnUOg0CToPYTy6Piz4FA9LZGOBQBRgNmTJ1ZlU3Dd0y2WB62S51mHUMY00XnXsrDnlbOuN5hTDl5dKrtn57ntKCyQPrImyccpZ4yRyZVYSLRRjgQw3stvG/eF+BcGgv1cnkiVVkR2DZg2e1TaNb6yEH+1i4HGgNQk1Rd8hxpGrSv10BGKuBgdI8V46n7rHD801eenSYhscJ0lhkLxKk/wgfqYbIDngNjUaiLXGWg7N8MNa8vm6K/2cWDhIxAIUtUDc1hPHdEg4HtMSnEZ62pA7BL0BspHp2DEeTr1BU5yqjj3MGJBUtoxHBxnAqoionXSS2Q17L861+rw==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
