---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA/iVrxeZFTGfIeYeybY8z7eKADMLDT3vTC36rXhfFGShEfoeEHpLhE4x1oJ7oHZJW/auztRawXZHvap8EztJhO94uImP4JWgaw8V44P7y3EuhYFVw8/b71iceYnmHAnK1TTO4JaVWk75B/dQrbJYooBNiex+sSGG8TaLLHRrKnaiosgpeXYBGN7Jykj5O9/hNoZ2qYtG7K5+2TxIGo6S1pQmIEGlVj3wiQxrSXXgYJfBoB7iXTE+0EpsUWXt06ivv0ptQorbDI+o7wlt2aaS6nMybrknXTrb59tWFlueOzOnPqozhrLPYCSk+RC9n6ZEg9PcS/BvR1ELGuhdlQK53FiAckqu7hEuH+IidQKbPr9Z4YtX8N/6YWMbiDIvetZJkqzMsFLNsssdsX5NlbNhUEB9MEq3I/DLpV96YV3F18vOBNFrZvMC++bAgWQpDx27WVkmUB0mjJiXSnlM3dIlyNpgLP0VqckbVE4PkXiGrhwB3oRX5UyBCP2fc2SMbUzCQrjTBykfGK0OotbLLC9FlVo3yhnu1Yx0Jx3ntnIrtg7frjJNuToqhnwENuPyjvBFq7VvovaawDTJF3RcTj/h6+dX/pj6dL9PyQZP6L05rowUcvpfvD3WBzvt4k8nY/TsP/t2EBzuFsAvHFZiml9LkMD10eyjdTfb7h7vWc0WZsU+iu82gLVqRVi6F2aqIzPS+G7+eAI19HUSLu0Il8fVN0ObxMk9qEBtwladq7PcSazN2w3Iz3KDeG
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
