---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pi-auth
  namespace: pi
spec:
  encryptedData:
    auth.json: AgCwkRkhiT0A0ViU4cVZz2wNYS9NRGpFVWJkVTM7DhwnFy1a2Lqs/LfFTpRYlwdMjTp3ja57ApsLfvPrVQ0o9/I2HmBKsPi0lx9oRmY8f9zyhY0bSv3GT/mfuwNLCaJTm1+NJSwkS7FsyGqUpmECx8WgaW3dJ5sSYn4Hgs9RSNYtnXoU1e2yYSW0MIZoDsVE8ilMRpYYpGW3vdYt4v7AhSxDIzTI6HX4gPF+OX2e0y3lc8pKBrpAEHFLd2G27+HQginDHzOipWZwrhnIMBTcpdyrhE2PqsUf3LHsj91qf11k+3NMI9l9Bp18CrKZhw3TetM1hQcQPfhYCPlI+G2FZywGb2FUVSh++3dEtLDDNpfC0FFG7bhS3WpTFRXZ4CmDeZn95M7lA9dOZEwdacsTw0TIaNysInzthGPqBSd4bAMnzzfkW/XGa+x5F3OWsdPh+30sZYFIQi3Z7pF7/ygKYVO8ejySIQ0W69UiXrQ4AUGRJGsl4bk82qgxLWaFEy9TxMtVdSbYw//KxWmWeX4u4iKmqifKG2SfN0QQpNi/fM6gzDSGcyUstsKIn/V9sGPXME52GNqYC6TsDagEJTpaDqcfkw5HSMS60MUOVnbnSzzsbXnPi0w6mXjN9j3Q0qh1Xq5TQJzOzG5KqCDzdomiTloP3I5uaTWXoCzeGac0h/oGWfbw3UumOPinvYFuytNlI61JkhFoRQUjaMCG8VEUapHepwwB9xkT2UGpmNp4QZW6k91BMX4KlZUzi7NgsSO1YqSAziAEUs/7nmRy2f0D1YaRQT1Wg0PUm7bKo1jqJcAHExRVj00blGyUx0gBsIA6NWTcPZ5FT1k2/rWThg2fwsHJsiKW3zb8A/SNE1nGoA3cMOqqLTThGutaezbRb1DGGy3LMOXRTVijxq7mekiI0RHRZJhYzqe9l+adhZAA4sb68kahPRR5/yz+FeIJri9W0dB7RfNigaN8V/F2d6o9uppNxar43J3mAkoyOWoFmQrl
  template:
    metadata:
      name: pi-auth
      namespace: pi
    type: Opaque
