apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-home
  namespace: pi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client
