---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-secrets
  namespace: staging
spec:
  encryptedData:
    RAILS_MASTER_KEY: AgCtU1SbwJcmG9Efd7QTXIcnWuRFgltd5fOiW3mLGAFlLYa4uNf7J8+gWaqnMj9UwVmgracroZYLic2zhG2Ks37z4O94fBaGEuqECGXu8S25TCHU9f9eNni8figmGo3Oyo11bMBMIG9E54fiFDbo1zoqX8qxdVZVetbqgWrP8litJAMrre6gj2qkldcw/FIgW0nQ8zdp3w2Muysajd1HtbtWOfV6ncJmuPmgbFcKJvTEG8lkHQKqsWUS8+2EshpZ2f2QLJ8CSA7L7vEUYUCLKRl5iG33JK2NVAOO74tn/F79YBAZc72smDE0K3U90BG8+c+nsKnMCnOVflOnucA3cGE+yq3vpBxbGtvBZbUB7X5XxWrk/2ChVPHKEyh3FtcR1euqbnCdaO6L/MUJ96Elmk2AbbpY3j2BbZz7lD3pBj5qZSQ48ZGv2Mg11Distk5bd2/UazfTAmXKP5QxNZc48NutABwXtNF0Ee+4akX+FBCUxiaW5U6BlR7xzvcY+TG9fIA3j2+Qnslu4FsHTSXfy6k3jBWeeOMnhQoB1wdm5uzi8UjfouP7MMziQaWoEaUQxbpLHEF134402OZzp+bLrkBH0I2fzjLv01d7Ehhrs0N+ohuMtQVrsFe9tJrLXnaRQKeuUH3pK4okxB7XjoolbjylsYJ0AvAD/r2sCGrwWT62oEqHBmAXjmhX16Y/KrhTh3RWf5oCiQ8Vew+72VmgFsSJt3GB478+oGgbbIPIQqfjGA==
  template:
    metadata:
      name: home-secrets
      namespace: staging
